Выполняет задание 2.19
htmlacademy-htmlcss/1687397-sedona-31 pull request #2
Opened 2021-05-26 11:18 UTC by KogutYogurt

2021-05-26 13:40 UTC, Vallek requested changes
Привет! Поздравляю с первым полноценным заданием:) В целом неплохо, много сделано верно. 

Общие замечания (остальное в коде):

1. Прежде всего нужно прогонять код через валидатор https://validator.w3.org/nu/ Это позволит найти много проблем с вложенностью и тегами. В данном случае нужно сначала исправить первые ошибки, иначе валидатор не может все проверить. Всегда стоит исправлять сверху вниз, потому что  одни ошибки могут создавать другие.
2. Логотип - это не часть списка по ТЗ. Кроме того непосредственно в ul можно вкладывать только li.
3. Обрати внимание, что "жилье, еда и сувениры" - это не часть общего списка, а часть первого пункта этого списка. Можно делать подпункты вставив ul внутрь li.
4. Не хватает кнопки "ПОИСК ГОСТИНИЦЫ В СЕДОНЕ".
5. И карты (достаточно просто картинки)

Если что-то непонятно или неполучается, то пиши и можем провести консультацию.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +		<h2>Седона — небольшой городок в Аризоне, заслуживающий большего! </h2>
Здесь и далее: В код попали лишние символы переноса строк с макета. Их просто нужно удалить.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +	<h1>СЕДОНА</h1>
Такого заголовка тут нет. Но его можно будет сделать невидимым и доступным. Про это вам позже должны рассказать.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +	<a><img src="" width="187.74" height="44.75" alt=«Логотип «Welcome»> </a> <br>
Это все можно сделать одной картинкой. Молодец, что в alt текст добавила. Только нельзя использовать двойные кавычки внутри значения атрибута (обрати внимание на подсветку). Такие символы нужно заменять на спец. код. Можно тут найти https://unicode-table.com/ru/

2021-05-26 13:40 UTC, Vallek commented on index.html
> +      	<p>-№1-</p>
Нумерацию можно будет потом сделать через css. Но можешь пока так оставить.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +        	 <figure> <a href="#">
Эти картинки не должны быть ссылками. Я бы не стал усложнять figure:) Можно просто img сделать.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +			<li><a href="blank.html">Информация</li>
Здеьс и далее: не хватает закрывающего тега.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +      </a>
Здесь и далее: закрывающий тег не может выходить за пределы родителя.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +    		<input type="date" name="calendar" value="2017-04-27">
Здесь и далее: у разных инпутов должны быть разные имена (взрослые и дети, заезд и выезд). Иначе сервер не поймет что где. Посмотри как это выглядит, после отправки.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +</main>
Футер - не часть main. main - это уникальный контент страницы. А футер и шапка повторяются.

2021-05-26 13:40 UTC, Vallek commented on index.html
> +        <img src="" width="75" height="72" alt="Домик icon-1"></a>
Иконки лушче будет потом сделать через css псевдоэлементы.

2021-05-27 18:43 UTC, KogutYogurt commented on index.html
> +		<h2>Седона — небольшой городок в Аризоне, заслуживающий большего! </h2>
Поправила

2021-05-27 18:54 UTC, KogutYogurt commented on index.html
> +    		<input type="date" name="calendar" value="2017-04-27">
здесь не поняла как для Дат заезд выезд сделать имена в input

2021-05-28 12:11 UTC, Vallek requested changes
Остаются ошибки валидации. Нужно все красные исправить. На желтые не обращай внимания. А именно:
1. Пустые src. Пока можно поставить заглушки. В задании есть пример.
2. Размеры в html атрибутах указываются целыми числами.
3. Ошибки в тегах
4. В форме значение for должно указывать на id инпута.

Из остальных замечаний не все исправлено:
1. Картинка карты
2. Остальное в коде

И если что-то непонятно лучше сразу провести консультацию)

2021-05-28 12:11 UTC, Vallek commented on index.html
> +	<a><img src="" width="187.74" height="44.75" alt="Логотип Welcome"> </a> <br>
Это одна картинка. Ссылки и переносы строк тут не нужны.

2021-05-30 18:42 UTC, merged